### ISSUE TITLE
Style-Property don't work

### ISSUE THREAD

**Issue by JarJarBinkz** [UXDivers/Grial-UI-Kit-Support-And-Issues#15]
Hello,

I bought the Grail-UI-Kit and create my own pages based on Grial-UI-Kit. I use for the controls the Style property and the App.xaml file. In Gorilla Player the page is displayed correctly. When I compile it and run it on my phone the style property ignored. What should I do with the style works properly ?

**Comment by jpbrocca** [comment]
Hi, 

Are you building your project based on Grial sample or you just started to add Grial stuff to your project ?

In case you started a new project from scratch please take a look at the following document:
https://github.com/UXDivers/Grial-UI-Kit-Support-And-Issues/wiki/Creating-a-new-project-using-Grial

For more additional info about adding Grial stuff to your project please also check:

https://github.com/UXDivers/Grial-UI-Kit-Support-And-Issues/wiki/Adding-Grial-on-existing-project:-Setting-up-Grial-theme-required-files

https://github.com/UXDivers/Grial-UI-Kit-Support-And-Issues/wiki/Getting-started-adding-Grial-to-an-existing-project

Let me know how it goes.

Regards,
JP

**Comment by JarJarBinkz** [comment]
Hi,

I started with a new project and add the Grial stuff. I try what you write, but is not working.

I have tested the problem in addition to your example " MyCoolCompanyApp " .

**My modified App.xaml.cs file:**
```
public App ()
{
	// The root page of your application
	MainPage = new MyPeople();
//	MainPage = new MyCoolCompanyPage();
}
```

**My modified MyCoolCompanyApp.xaml.cs file:**
```
public partial class MyPeople : ContentPage
{
	public MyPeople ()
	{
		InitializeComponent ();
		BindingContext = new [] { new { Name = "Pam Tailor", City = "SIDNEY", Department = "Design", Age = 32, Followers = 24,  Photo = "friend_thumbnail_75.jpg" }};
	}
}

The Style-Property don't work on my phone. In Gorilla Player all works.


**With Gorilla Player:**
![mycoolcompanyapp_with_gorillaplayer](https://cloud.githubusercontent.com/assets/16030219/12717583/157381ca-c8e9-11e5-8a32-c99839a457ea.png)

**On the Phone:**
![mycoolcompanyapp_onthephone](https://cloud.githubusercontent.com/assets/16030219/12717585/1872fb9e-c8e9-11e5-9000-a67a36231618.png)

**Comment by JarJarBinkz** [comment]
**With Gorilla Player:**
![mycoolcompanyapp_with_gorillaplayer](https://cloud.githubusercontent.com/assets/16030219/12717583/157381ca-c8e9-11e5-8a32-c99839a457ea.png)

**On the Phone:**
![mycoolcompanyapp_onthephone](https://cloud.githubusercontent.com/assets/16030219/12717585/1872fb9e-c8e9-11e5-9000-a67a36231618.png)

**Comment by jpbrocca** [comment]
Hi again,

I am confused...It seems you are using MyCoolCompanyApp as your project ?
This is the sample provided with Gorilla Player and it is something initially not related with Grial UI kit.

Can you preview Grial UI Kit sample on Gorilla ?
Could you attach a screen capture of it ?

Thanks

**Comment by JarJarBinkz** [comment]
Hi,

sorry, was my mistake. Have now run everything on. My project and all samples are running now.

Thank you

**Comment by jpbrocca** [comment]
OK, I will close this since it seems there was no bug afterall :)
Thanks
