### ISSUE TITLE
How do I use Icons?

### ISSUE THREAD

**Issue by homerokzam** [UXDivers/Grial-UI-Kit-Support-And-Issues#16]
I followed the documentation "Using Icons", but it still fails. How do I use this feature?

Here's a link to my code: https://github.com/homerokzam/TestIcon

Thank you so much.
Homero

**Comment by homerokzam** [comment]
???

**Comment by jpbrocca** [comment]
Hi @homerokzam sorry about the delay on this.

Meanwhile we review your sample could you take a look at #10 ?

Thanks!

**Comment by homerokzam** [comment]
It's working!!!

Thank you so much.
Homero

**Comment by jpbrocca** [comment]
Ok, did the link I sent you (#10) helped you?

Should I close this issue now?
Thanks.
