### ISSUE TITLE
Cannot build the sample app (Grial 1.2 update)

### ISSUE THREAD

**Issue by kunjal29** [UXDivers/Grial-UI-Kit-Support-And-Issues#18]
I downloaded update 1.2 and tried to build the sample app. I am getting lots of errors. I made sure to extract all the directories as per the solution to the earlier issue on this wiki.

I am running VS2015 on Windows 10 Pro. with Xamarin 4.0.1.93

**Comment by jpbrocca** [comment]
Hi @kunjal29 

Did you updated packages to support xamarin forms 2.0?

If you did that then please attach a screen shot or paste the errors here?

Thanks,
JP

**Comment by kunjal29** [comment]
I downloaded the 1.2 update from your site which already has the references to xamarin forms 2.0.

Digging deeper I've found that restoring the nuget packages for Xamarin.Android don't get installed properly. Will update here if I get it sorted out.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unexpected error - Please file a bug report at http://bugzilla.xamarin.com. Reason: System.IO.FileNotFoundException: Could not load assembly 'UXDivers.Artina.Grial, Version=, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?	Grial.Droid

**Comment by kunjal29** [comment]
After removing all the nuget packages from the Grial.Droid project I am getting this error trying to install the Xamarin.Android.Support.v4 package

PM> Install-Package Xamarin.Android.Support.v4 -Version 23.0.1.3
Attempting to gather dependencies information for package 'Xamarin.Android.Support.v4.23.0.1.3' with respect to project 'Grial.Droid', targeting 'MonoAndroid,Version=v6.0'
Attempting to resolve dependencies for package 'Xamarin.Android.Support.v4.23.0.1.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Xamarin.Android.Support.v4.23.0.1.3'
Resolved actions to install package 'Xamarin.Android.Support.v4.23.0.1.3'
Install failed. Rolling back...
Package 'Xamarin.Android.Support.v4.23.0.1.3 : ' does not exist in project 'Grial.Droid'
Package 'Xamarin.Android.Support.v4.23.0.1.3 : ' does not exist in folder 'C:\Projects\grial-uikit-1.2.0\samples\Grial\packages'
Install-Package : Could not install package 'Xamarin.Android.Support.v4 23.0.1.3'. You are trying to install this package into a 
project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Xamarin.Android.Support.v4 -Version 23.0.1.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by jpbrocca** [comment]
Hi @kunjal29, I am sorry to hear that.
While I initially tried to update to Xamarin Forms 2.0 I had similar issues on Android project.
I was working with Xamarin Studio but I remember similar issues to what you described using VS.
What worked for me at that time was to manually remove all packages, then add Xamarin Forms 2.0.

I have found on internet that a guy had similar issues on VS and this is what worked for him on VS:

> I have had the same issue. I simply closed my solution, removed the packages folder from the solution, opened solution (in my case VS2015) and rebuilt. It worked for me. Good luck!

On another occasion I updated packages and got similar issues to yours, what worked for me that time was to only update xamarin forms package on Android and then the remaining packages were updated automatically in the right sequence and finally worked. 

Last but not least, here is a more detailed explanation in case all the previous fails:
http://stackoverflow.com/questions/33946778/android-resource-issues-after-upgrading-to-xamarin-forms-2-0

Regards,
JP

**Comment by kunjal29** [comment]
Looks like it is a bug with the latest Nuget Manager for VS2015 which is due to be fixed with the 3.4 release. No idea on the ETA for that.

Would I be able to fix the build issues if I download the various Xamarin.Android nuget packages and extract the DLLs and manually add references to them?

Will update you here if it works.

**Comment by kunjal29** [comment]
Managed to compile this on a machine with an earlier version of Xamarin Forms and Nuget Manager. So the issue is with Nuget and not the 1.2 update. Please go ahead and close this issue.
