### ISSUE TITLE
Button TextColor not being processed for a ButtonStyle

### ISSUE THREAD

**Issue by james-lavery** [UXDivers/Grial-UI-Kit-Support-And-Issues#19]
I've got a BaseButtonStyle defined in my App.xaml:

```
			<Style
				x:Key     ="BaseButtonStyle"
				TargetType="Button">
				<Setter
					Property="FontSize"
					Value   ="{StaticResource BaseFontSize}" />
				<Setter
					Property="BackgroundColor"
					Value   ="{StaticResource BrandColor}">
				</Setter>
				<Setter
					Property="HeightRequest"
					Value   ="{StaticResource BaseButtonHeight}" />
				<Setter
					Property="TextColor"
					Value   ="Black">
				</Setter>
			</Style>
```
and this works fine when previewing with Gorilla. However, when running the actual app, the TextColor isn't being set - in fact, the TextColor seems to be the same as the button!

This is happening on both Android and iOS.

Screenshots below.
Application:
![simulator screen shot 18 feb 2016 11 28 05](https://cloud.githubusercontent.com/assets/1755678/13142442/fc8593b6-d634-11e5-9064-fbfbfe55812c.png)

Gorilla:
![simulator screen shot 18 feb 2016 11 43 57](https://cloud.githubusercontent.com/assets/1755678/13142457/11aa2e0a-d635-11e5-824a-4e3f7dc6fa6a.png)

**Comment by jpbrocca** [comment]
Hi James,

what happens if you replace -just to test- the button's text color with an specific one i.e.: "White" ?

**Comment by james-lavery** [comment]
Hi JP,
Just tried that, and have the same problem.  Shows as white using Gorilla (embedded in the app using the SDK), no text when running the normal application.

The XAML I used is:

```
<Button
	WidthRequest     ="90"
	Style            ="{DynamicResource BaseButtonStyle}"
	HorizontalOptions="StartAndExpand"
	Text             ="{Binding DetailsButtonText}"
	TextColor="White" />
```

**Comment by jpbrocca** [comment]
Ok, could it be possible that the data -or the binding on the button- on the app could be wrong ?

**Comment by jpbrocca** [comment]
For the Text I mean

**Comment by james-lavery** [comment]
Doh! Thanks - that was the problem.

**Comment by jpbrocca** [comment]
Glad it helped! (and to to see it was not a bug on Grial :P)

**Comment by james-lavery** [comment]
No problem - BTW, Gorilla is proving very useful. I'll do a blog post on it soon!

**Comment by jpbrocca** [comment]
Wow, that would be great James! :)
Thanks for helping us to spread the word!
Let me know if you need any content such as images, logos, etc.

Cheers!
